version: '3.8'

services:
  api:
    build: .
    container_name: onco-assist-api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - TIDB_HOST=${TIDB_HOST}
      - TIDB_PORT=${TIDB_PORT}
      - TIDB_USER=${TIDB_USER}
      - TIDB_PASSWORD=${TIDB_PASSWORD}
      - TIDB_DATABASE=${TIDB_DATABASE}
      - TIDB_SSL_CA_PATH=/app/certs/ca-cert.pem
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REFRESH_TOKEN=${GOOGLE_REFRESH_TOKEN}
      - GOOGLE_ACCESS_TOKEN=${GOOGLE_ACCESS_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_FROM_NUMBER=${TWILIO_FROM_NUMBER}
    volumes:
      - ./certs:/app/certs:ro
      - ./logs:/app/logs
    ports:
      - "3000:3000"
    networks:
      - onco-assist-network

networks:
  onco-assist-network:
    driver: bridge
