version: '3.8'

services:
  onco-assist:
    build: .
    container_name: onco-assist
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./certs:/app/certs
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
    networks:
      - onco-assist-network

  redis:
    image: redis:7-alpine
    container_name: onco-assist-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - onco-assist-network

  # Optional: Add monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: onco-assist-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - onco-assist-network
    profiles:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: onco-assist-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - onco-assist-network
    profiles:
      - monitoring

volumes:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  onco-assist-network:
    driver: bridge
